version: '3.8'

services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: candelaria
      MYSQL_DATABASE: dcs
      MYSQL_USER: candelaria
      MYSQL_PASSWORD: candelaria
    ports:
      - "3306:3306"
    volumes:
      - ./database:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: candelaria
    ports:
      - "8080:80"
    depends_on:
      - db

  vpn-forticlient:
    build:
      context: DCS-Candelaria/Services/VpnForti
    restart: always
    depends_on:
      - db
    environment:
      - ENVIRONMENT=production

  dcs-candelaria_switches:
    build:
      context: DCS-Candelaria/Services/Switches
    restart: always
    depends_on:
      - db
    environment:
      - ENVIRONMENT=production
        
  dcs-candelaria_clients:
    build:
      context: DCS-Candelaria/Services/Clientes
    restart: always
    depends_on:
      - db
    environment:
      - ENVIRONMENT=production
      
  ups:
    build:
      context: DCS-Candelaria/Services/Ups
    restart: always
    depends_on:
      - db
    environment:
      - ENVIRONMENT=production
      
  mesh:
    build:
      context: DCS-Candelaria/Services/Mesh
    restart: always
    depends_on:
      - db
    environment:
      - ENVIRONMENT=production
      
  camaras:
    build:
      context: DCS-Candelaria/Services/Devices
    restart: always
    depends_on:
      - db
    environment:
      - ENVIRONMENT=production
    
  backend-api-rest:
    build:
      context: Backend
    ports:
      - '3000:3000'
    restart: always
    environment:
      - NODE_ENV=production
    command: sh -c "npx sequelize-cli db:migrate && node index.js"
      
  frontend-react:
    build:
      context: Front
    ports:
      - '4000:80'
    restart: always
    # environment: Este se define en el archivo .env

  wan:
    build:
      context: DCS-Candelaria/Services/Wan
    restart: always
    depends_on:
      - db
    environment:
      - ENVIRONMENT=production

  firewalls:
    build:
      context: DCS-Candelaria/Services/Firewalls
    restart: always
    depends_on:
      - db
    environment:
      - ENVIRONMENT=production
